'use strict'

// Common keys
const OUTPUT_FILE_NAME_KEY = 'outputFileName',
  NEW_RELIC_API_KEY_VAR = 'NEW_RELIC_API_KEY',
  NEW_RELIC_ACCOUNT_ID_VAR = 'NEW_RELIC_ACCOUNT_ID',
  NEW_RELIC_REGION_KEY = 'region',
  NEW_RELIC_REGION_VAR = 'NEW_RELIC_REGION',
  NEW_RELIC_REGION_US = 'US',
  NEW_RELIC_REGION_EU = 'EU',
  DEFAULT_NEW_RELIC_REGION = NEW_RELIC_REGION_US,
  LOG_LEVEL_VAR = 'LOG_LEVEL',
  SECRET_NAME_VAR = 'SECRET_NAME'

// Engine option constants
const MANIFEST_FILE_PATH_OPTION = 'manifestFilePath',
  MANIFEST_FILE_PATH_VAR = 'MANIFEST_FILE_PATH',
  OUTPUT_FILE_NAME_OPTION = OUTPUT_FILE_NAME_KEY,
  DASHBOARD_IDS_OPTION = 'dashboardIds',
  DASHBOARD_IDS_VAR = 'DASHBOARD_IDS',
  NRQL_QUERY_OPTION = 'nrqlQuery',
  NRQL_QUERY_VAR = 'NRQL_QUERY',
  CHANNEL_IDS_OPTION = 'channelIds',
  CHANNEL_IDS_VAR = 'CHANNEL_IDS',
  SOURCE_NERDLET_ID_OPTION = 'sourceNerdletId',
  SOURCE_NERDLET_ID_VAR = 'SOURCE_NERDLET_ID',
  PUBLISH_CONFIG_IDS_OPTION = 'publishConfigIds',
  PUBLISH_CONFIG_IDS_VAR = 'PUBLISH_CONFIG_IDS',
  DEFAULT_PUBLISH_CONFIG_ID = 'default'

// Output formats
const OUTPUT_FORMAT_HTML = 'html',
  OUTPUT_FORMAT_CSV = 'csv',
  OUTPUT_FORMAT_JSON = 'json'

// Manifest file constants
const REPORT_IDS_OPTION = 'reportIds',
  REPORT_IDS_VAR = 'REPORT_IDS',
  DEFAULT_MANIFEST_FILE_NAME = 'manifest.json',
  DEFAULT_MANIFEST_FILE_PATH = `${DEFAULT_MANIFEST_FILE_NAME}`,
  DEFAULT_MANIFEST_ID = 'default-manifest'

// Dashboard generator constants
const DEFAULT_DASHBOARD_REPORT_ID = 'dashboard-report',
  COMBINE_PDFS_KEY = 'combinePdfs'

// Query generator constants
const DEFAULT_QUERY_REPORT_ID = 'query-report'

// Query renderer constants
const QUERY_RESULTS_FORMAT_KEY = 'queryResultsFormat',
  QUERY_RESULTS_FORMAT_VAR = 'QUERY_RESULTS_FORMAT',
  QUERY_RESULTS_FORMAT_CSV = OUTPUT_FORMAT_CSV,
  QUERY_RESULTS_FORMAT_JSON = OUTPUT_FORMAT_JSON,
  QUERY_RESULTS_FORMAT_HTML = OUTPUT_FORMAT_HTML,
  QUERY_RESULTS_FORMAT_DEFAULT = QUERY_RESULTS_FORMAT_CSV,
  QUERY_RESULTS_HTML_MAX_ROWS_KEY = 'queryResultsHtmlMaxRows',
  QUERY_RESULTS_HTML_MAX_ROWS_VAR = 'QUERY_RESULTS_HTML_MAX_ROWS',
  QUERY_RESULTS_HTML_MAX_ROWS_DEFAULT = 25

// Nerdstorage constants
const MANIFESTS_COLLECTION_NAME = 'manifests'

// Formatter constants
const FORMATTER_REPORT_ID_KEY = 'REPORT_ID',
  FORMATTER_REPORT_NAME_KEY = 'REPORT_NAME',
  FORMATTER_PUBLISH_CONFIG_ID_KEY = 'PUBLISH_CONFIG_ID',
  FORMATTER_PUBLISH_CONFIG_NAME_KEY = 'PUBLISH_CONFIG_NAME',
  FORMATTER_CHANNEL_ID_KEY = 'CHANNEL_ID',
  FORMATTER_CHANNEL_NAME_KEY = 'CHANNEL_NAME',
  FORMATTER_TIMESTAMP_KEY = 'TIMESTAMP',
  FORMATTER_DATETIME_KEY = 'DATETIME',
  FORMATTER_RESULTS_KEY = 'RESULTS',
  FORMATTER_RESULTS_CSV_FORMATTED = 'RESULTS_CSV_FORMATTED'

// Email channel constants
const EMAIL_SMTP_SERVER_KEY = 'emailSmtpServer',
  EMAIL_SMTP_SERVER_VAR = 'EMAIL_SMTP_SERVER',
  EMAIL_SMTP_PORT_KEY = 'emailSmtpPort',
  EMAIL_SMTP_PORT_VAR = 'EMAIL_SMTP_PORT',
  EMAIL_SMTP_SECURE_KEY = 'emailSmtpSecure',
  EMAIL_SMTP_SECURE_VAR = 'EMAIL_SMTP_SECURE',
  EMAIL_SMTP_USER_VAR = 'EMAIL_SMTP_USER',
  EMAIL_SMTP_PASS_VAR = 'EMAIL_SMTP_PASS',
  EMAIL_FROM_VAR = 'EMAIL_FROM',
  EMAIL_TO_VAR = 'EMAIL_TO',
  EMAIL_CC_VAR = 'EMAIL_CC',
  EMAIL_SUBJECT_VAR = 'EMAIL_SUBJECT',
  EMAIL_BODY_KEY = 'body',
  EMAIL_SMTP_PORT_DEFAULT = 587,
  EMAIL_FROM_KEY = 'from',
  EMAIL_TO_KEY = 'to',
  EMAIL_CC_KEY = 'cc',
  EMAIL_SUBJECT_KEY = 'subject',
  EMAIL_FORMATTER_FROM_KEY = EMAIL_FROM_VAR,
  EMAIL_FORMATTER_TO_KEY = EMAIL_TO_VAR,
  EMAIL_FORMATTER_CC_KEY = EMAIL_CC_VAR,
  EMAIL_FORMATTER_SUBJECT_KEY = EMAIL_SUBJECT_VAR

// File channel constants
const FILE_DEST_DIR_VAR = 'FILE_DEST_DIR',
  FILE_DEST_DIR_KEY = 'destDir',
  FILE_DEST_DIR_DEFAULT = '.'

// S3 channel constants
const S3_DEST_BUCKET_VAR = 'S3_DEST_BUCKET',
  S3_DEST_BUCKET_KEY = 'bucket',
  S3_SOURCE_BUCKET_VAR = 'S3_SOURCE_BUCKET',
  S3_SOURCE_BUCKET_KEY = 'sourceBucket'

// Slack channel constants
const SLACK_WEBHOOK_URL = 'SLACK_WEBHOOK_URL',
  SLACK_MESSAGE_KEY = 'message'

// Webhook channel constants
const WEBHOOK_URL_KEY = 'webhookUrl',
  WEBHOOK_URL_VAR = 'WEBHOOK_URL',
  WEBHOOK_HTTP_METHOD_KEY = 'webhookHttpMethod',
  WEBHOOK_HTTP_METHOD_VAR = 'WEBHOOK_HTTP_METHOD',
  WEBHOOK_HTTP_METHOD_DEFAULT = 'POST',
  WEBHOOK_HTTP_BASIC_USER_VAR = 'WEBHOOK_HTTP_BASIC_USER',
  WEBHOOK_HTTP_BASIC_PASS_VAR = 'WEBHOOK_HTTP_BASIC_PASS',
  WEBHOOK_HEADER_KEY = 'webhookHeader',
  WEBHOOK_HEADER_VAR = 'WEBHOOK_HEADER'

module.exports = {

  // Common keys
  OUTPUT_FILE_NAME_KEY,
  NEW_RELIC_API_KEY_VAR,
  NEW_RELIC_ACCOUNT_ID_VAR,
  NEW_RELIC_REGION_KEY,
  NEW_RELIC_REGION_VAR,
  NEW_RELIC_REGION_US,
  NEW_RELIC_REGION_EU,
  DEFAULT_NEW_RELIC_REGION,
  LOG_LEVEL_VAR,
  SECRET_NAME_VAR,

  // Engine options
  MANIFEST_FILE_PATH_OPTION,
  MANIFEST_FILE_PATH_VAR,
  OUTPUT_FILE_NAME_OPTION,
  DASHBOARD_IDS_OPTION,
  DASHBOARD_IDS_VAR,
  NRQL_QUERY_OPTION,
  NRQL_QUERY_VAR,
  CHANNEL_IDS_OPTION,
  CHANNEL_IDS_VAR,
  SOURCE_NERDLET_ID_OPTION,
  SOURCE_NERDLET_ID_VAR,
  PUBLISH_CONFIG_IDS_OPTION,
  PUBLISH_CONFIG_IDS_VAR,
  DEFAULT_PUBLISH_CONFIG_ID,

  // Output formats
  OUTPUT_FORMAT_HTML,
  OUTPUT_FORMAT_CSV,
  OUTPUT_FORMAT_JSON,

  // Manifest file constants
  REPORT_IDS_OPTION,
  REPORT_IDS_VAR,
  DEFAULT_MANIFEST_FILE_NAME,
  DEFAULT_MANIFEST_FILE_PATH,
  DEFAULT_MANIFEST_ID,

  // Dashboard generator constants
  DEFAULT_DASHBOARD_REPORT_ID,
  COMBINE_PDFS_KEY,

  // Query generator constants
  DEFAULT_QUERY_REPORT_ID,

  // Query renderer constants
  QUERY_RESULTS_FORMAT_KEY,
  QUERY_RESULTS_FORMAT_VAR,
  QUERY_RESULTS_FORMAT_CSV,
  QUERY_RESULTS_FORMAT_JSON,
  QUERY_RESULTS_FORMAT_HTML,
  QUERY_RESULTS_FORMAT_DEFAULT,
  QUERY_RESULTS_HTML_MAX_ROWS_KEY,
  QUERY_RESULTS_HTML_MAX_ROWS_VAR,
  QUERY_RESULTS_HTML_MAX_ROWS_DEFAULT,

  // Nerdstorage constants
  MANIFESTS_COLLECTION_NAME,

  // Formatters constants
  FORMATTER_REPORT_ID_KEY,
  FORMATTER_REPORT_NAME_KEY,
  FORMATTER_PUBLISH_CONFIG_ID_KEY,
  FORMATTER_PUBLISH_CONFIG_NAME_KEY,
  FORMATTER_CHANNEL_ID_KEY,
  FORMATTER_CHANNEL_NAME_KEY,
  FORMATTER_TIMESTAMP_KEY,
  FORMATTER_DATETIME_KEY,
  FORMATTER_RESULTS_KEY,
  FORMATTER_RESULTS_CSV_FORMATTED,

  // Email channel constants
  EMAIL_SMTP_SERVER_KEY,
  EMAIL_SMTP_SERVER_VAR,
  EMAIL_SMTP_PORT_KEY,
  EMAIL_SMTP_PORT_VAR,
  EMAIL_SMTP_SECURE_KEY,
  EMAIL_SMTP_SECURE_VAR,
  EMAIL_SMTP_USER_VAR,
  EMAIL_SMTP_PASS_VAR,
  EMAIL_FROM_VAR,
  EMAIL_TO_VAR,
  EMAIL_CC_VAR,
  EMAIL_SUBJECT_VAR,
  EMAIL_SMTP_PORT_DEFAULT,
  EMAIL_FROM_KEY,
  EMAIL_TO_KEY,
  EMAIL_CC_KEY,
  EMAIL_SUBJECT_KEY,
  EMAIL_BODY_KEY,
  EMAIL_FORMATTER_FROM_KEY,
  EMAIL_FORMATTER_TO_KEY,
  EMAIL_FORMATTER_CC_KEY,
  EMAIL_FORMATTER_SUBJECT_KEY,

  // File channel constants
  FILE_DEST_DIR_VAR,
  FILE_DEST_DIR_KEY,
  FILE_DEST_DIR_DEFAULT,

  // S3 channel constants
  S3_DEST_BUCKET_VAR,
  S3_DEST_BUCKET_KEY,
  S3_SOURCE_BUCKET_VAR,
  S3_SOURCE_BUCKET_KEY,

  // Slack channel constants
  SLACK_WEBHOOK_URL,
  SLACK_MESSAGE_KEY,

  // Webhoook channel constants
  WEBHOOK_URL_KEY,
  WEBHOOK_URL_VAR,
  WEBHOOK_HTTP_METHOD_KEY,
  WEBHOOK_HTTP_METHOD_VAR,
  WEBHOOK_HTTP_METHOD_DEFAULT,
  WEBHOOK_HTTP_BASIC_USER_VAR,
  WEBHOOK_HTTP_BASIC_PASS_VAR,
  WEBHOOK_HEADER_KEY,
  WEBHOOK_HEADER_VAR,
}
