FROM alpine:3

# Build args
ARG CLI_ARGS
ARG CRON_ENTRY

# Install required packages
RUN apk add --no-cache \
      chromium \
      nss \
      freetype \
      harfbuzz \
      ca-certificates \
      ttf-freefont \
      nodejs \
      yarn
# Install node and make the app root
RUN apk add --no-cache \
    chromium \
    nss \
    freetype \
    harfbuzz \
    ca-certificates \
    ttf-freefont \
    nodejs \
    yarn \
    nodejs \
    npm

# Copy function code
COPY nr-reports-core /app/nr-reports-core/
COPY nr-reports-cli /app/nr-reports-cli/
COPY templates /app/nr-reports-cli/templates/
COPY include /app/nr-reports-cli/include

# Tell Puppeteer to skip installing Chrome. We'll be using the installed package.
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true \
    PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser

# Add user so we don't need --no-sandbox.
RUN addgroup -S pptruser && adduser -S -g pptruser pptruser \
    && mkdir -p /home/pptruser/Downloads /app \
    && chown -R pptruser:pptruser /home/pptruser \
    && chown -R pptruser:pptruser /app && \
    echo "${CRON_ENTRY}    cd /app/nr-reports-cli && node index.js ${CLI_ARGS}" > /crontab.txt && \
    /usr/bin/crontab -u pptruser /crontab.txt && \
    cd /app/nr-reports-core && \
    npm install --production && \
    cd /app/nr-reports-cli && \
    npm install --production

# Container entry
CMD /usr/sbin/crond -f -l 8 && tail -f /var/log/cron.log
